# Default values for console-website.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

images:
  core:
    repository: cr.openfuyao.cn/openfuyao/console-website
    pullPolicy: Always
    tag: latest
# resources: {}
resources:
  requests: 
    cpu: 50m
    memory: 50Mi
  limits:
    cpu: 500m
    memory: 100Mi

config:
  enableTLS: false
  tlsCert: |
    -----BEGIN CERTIFICATE-----
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    -----END CERTIFICATE-----
  tlsKey: |
    -----BEGIN PRIVATE KEY-----
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    -----END PRIVATE KEY-----
  rootCA: |
    -----BEGIN CERTIFICATE-----
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    -----END CERTIFICATE-----
